on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: publish to yvdv.pages.dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run a build step here if your project requires

      - name: publish to yvdv.dev
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 92a05401a5cae05c2a7c154ba929f56a
          projectName: yvdv
          directory: site/ 
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
